{
    "check_dependencies.py-python-check_dependencies.py-04BAEB7F1938341A2E1F940D0EB1C228BD82886E":  {
                                                                                                        "FilesHash":  "04BAEB7F1938341A2E1F940D0EB1C228BD82886E",
                                                                                                        "Error":  null,
                                                                                                        "Command":  "python check_dependencies.py",
                                                                                                        "Success":  false,
                                                                                                        "Output":  "C:\\Program Files\\Python311\\python.exe: can\u0027t open file \u0027D:\\\\dmarket_trading_bot\\\\check_dependencies.py\u0027: [Errno 2] No such file or directory",
                                                                                                        "Name":  "check_dependencies.py",
                                                                                                        "StartTime":  "\/Date(1744863129616)\/",
                                                                                                        "ExitCode":  2,
                                                                                                        "EndTime":  "\/Date(1744863129659)\/",
                                                                                                        "Duration":  {
                                                                                                                         "Ticks":  430396,
                                                                                                                         "Days":  0,
                                                                                                                         "Hours":  0,
                                                                                                                         "Milliseconds":  43,
                                                                                                                         "Minutes":  0,
                                                                                                                         "Seconds":  0,
                                                                                                                         "TotalDays":  4.9814351851851846E-07,
                                                                                                                         "TotalHours":  1.1955444444444445E-05,
                                                                                                                         "TotalMilliseconds":  43.0396,
                                                                                                                         "TotalMinutes":  0.00071732666666666665,
                                                                                                                         "TotalSeconds":  0.0430396
                                                                                                                     },
                                                                                                        "Timestamp":  {
                                                                                                                          "value":  "\/Date(1744863129659)\/",
                                                                                                                          "DisplayHint":  2,
                                                                                                                          "DateTime":  "17 апреля 2025 г. 7:12:09"
                                                                                                                      }
                                                                                                    },
    "flake8-python--m flake8 -04BAEB7F1938341A2E1F940D0EB1C228BD82886E":  {
                                                                              "FilesHash":  "04BAEB7F1938341A2E1F940D0EB1C228BD82886E",
                                                                              "Error":  null,
                                                                              "Command":  "python -m flake8 ",
                                                                              "Success":  false,
                                                                              "Output":  [
                                                                                             ".\\.venv\\Lib\\site-packages\\sympy\\polys\\numberfields\\resolvent_lookup.py: \"pyflakes[F]\" failed during execution due to RecursionError(\u0027maximum recursion depth exceeded\u0027)",
                                                                                             "Run flake8 with greater verbosity to see more details"
                                                                                         ],
                                                                              "Name":  "flake8",
                                                                              "StartTime":  "\/Date(1744863008284)\/",
                                                                              "ExitCode":  1,
                                                                              "EndTime":  "\/Date(1744863093822)\/",
                                                                              "Duration":  {
                                                                                               "Ticks":  855379526,
                                                                                               "Days":  0,
                                                                                               "Hours":  0,
                                                                                               "Milliseconds":  537,
                                                                                               "Minutes":  1,
                                                                                               "Seconds":  25,
                                                                                               "TotalDays":  0.000990022599537037,
                                                                                               "TotalHours":  0.023760542388888889,
                                                                                               "TotalMilliseconds":  85537.9526,
                                                                                               "TotalMinutes":  1.4256325433333334,
                                                                                               "TotalSeconds":  85.5379526
                                                                                           },
                                                                              "Timestamp":  {
                                                                                                "value":  "\/Date(1744863093825)\/",
                                                                                                "DisplayHint":  2,
                                                                                                "DateTime":  "17 апреля 2025 г. 7:11:33"
                                                                                            }
                                                                          },
    "check_common_errors.py-python-check_common_errors.py --output=reports/common_errors_report.txt-04BAEB7F1938341A2E1F940D0EB1C228BD82886E":  {
                                                                                                                                                    "FilesHash":  "04BAEB7F1938341A2E1F940D0EB1C228BD82886E",
                                                                                                                                                    "Error":  null,
                                                                                                                                                    "Command":  "python check_common_errors.py --output=reports/common_errors_report.txt",
                                                                                                                                                    "Success":  false,
                                                                                                                                                    "Output":  "C:\\Program Files\\Python311\\python.exe: can\u0027t open file \u0027D:\\\\dmarket_trading_bot\\\\check_common_errors.py\u0027: [Errno 2] No such file or directory",
                                                                                                                                                    "Name":  "check_common_errors.py",
                                                                                                                                                    "StartTime":  "\/Date(1744863133388)\/",
                                                                                                                                                    "ExitCode":  2,
                                                                                                                                                    "EndTime":  "\/Date(1744863133433)\/",
                                                                                                                                                    "Duration":  {
                                                                                                                                                                     "Ticks":  450414,
                                                                                                                                                                     "Days":  0,
                                                                                                                                                                     "Hours":  0,
                                                                                                                                                                     "Milliseconds":  45,
                                                                                                                                                                     "Minutes":  0,
                                                                                                                                                                     "Seconds":  0,
                                                                                                                                                                     "TotalDays":  5.213125E-07,
                                                                                                                                                                     "TotalHours":  1.2511499999999999E-05,
                                                                                                                                                                     "TotalMilliseconds":  45.0414,
                                                                                                                                                                     "TotalMinutes":  0.00075069,
                                                                                                                                                                     "TotalSeconds":  0.045041399999999995
                                                                                                                                                                 },
                                                                                                                                                    "Timestamp":  {
                                                                                                                                                                      "value":  "\/Date(1744863133433)\/",
                                                                                                                                                                      "DisplayHint":  2,
                                                                                                                                                                      "DateTime":  "17 апреля 2025 г. 7:12:13"
                                                                                                                                                                  }
                                                                                                                                                },
    "bandit-python--m bandit -r -04BAEB7F1938341A2E1F940D0EB1C228BD82886E":  {
                                                                                 "FilesHash":  "04BAEB7F1938341A2E1F940D0EB1C228BD82886E",
                                                                                 "Error":  null,
                                                                                 "Command":  "python -m bandit -r ",
                                                                                 "Success":  false,
                                                                                 "Output":  [
                                                                                                "usage: __main__.py [-h] [-r] [-a {file,vuln}] [-n CONTEXT_LINES]",
                                                                                                "                   [-c CONFIG_FILE] [-p PROFILE] [-t TESTS] [-s SKIPS]",
                                                                                                "                   [-l | --severity-level {all,low,medium,high}]",
                                                                                                "                   [-i | --confidence-level {all,low,medium,high}]",
                                                                                                "                   [-f {csv,custom,html,json,screen,txt,xml,yaml}]",
                                                                                                "                   [--msg-template MSG_TEMPLATE] [-o [OUTPUT_FILE]] [-v] [-d]",
                                                                                                "                   [-q] [--ignore-nosec] [-x EXCLUDED_PATHS] [-b BASELINE]",
                                                                                                "                   [--ini INI_PATH] [--exit-zero] [--version]",
                                                                                                "                   [targets ...]"
                                                                                            ],
                                                                                 "Name":  "bandit",
                                                                                 "StartTime":  "\/Date(1744863106937)\/",
                                                                                 "ExitCode":  2,
                                                                                 "EndTime":  "\/Date(1744863107565)\/",
                                                                                 "Duration":  {
                                                                                                  "Ticks":  6270742,
                                                                                                  "Days":  0,
                                                                                                  "Hours":  0,
                                                                                                  "Milliseconds":  627,
                                                                                                  "Minutes":  0,
                                                                                                  "Seconds":  0,
                                                                                                  "TotalDays":  7.2578032407407406E-06,
                                                                                                  "TotalHours":  0.00017418727777777777,
                                                                                                  "TotalMilliseconds":  627.0742,
                                                                                                  "TotalMinutes":  0.010451236666666667,
                                                                                                  "TotalSeconds":  0.6270742
                                                                                              },
                                                                                 "Timestamp":  {
                                                                                                   "value":  "\/Date(1744863107565)\/",
                                                                                                   "DisplayHint":  2,
                                                                                                   "DateTime":  "17 апреля 2025 г. 7:11:47"
                                                                                               }
                                                                             },
    "mypy-python--m mypy -04BAEB7F1938341A2E1F940D0EB1C228BD82886E":  {
                                                                          "FilesHash":  "04BAEB7F1938341A2E1F940D0EB1C228BD82886E",
                                                                          "Error":  null,
                                                                          "Command":  "python -m mypy ",
                                                                          "Success":  false,
                                                                          "Output":  [
                                                                                         "usage: mypy [-h] [-v] [-V] [more options; see below]",
                                                                                         "            [-m MODULE] [-p PACKAGE] [-c PROGRAM_TEXT] [files ...]",
                                                                                         "mypy: error: Missing target module, package, files, or command."
                                                                                     ],
                                                                          "Name":  "mypy",
                                                                          "StartTime":  "\/Date(1744863101811)\/",
                                                                          "ExitCode":  2,
                                                                          "EndTime":  "\/Date(1744863103217)\/",
                                                                          "Duration":  {
                                                                                           "Ticks":  14052796,
                                                                                           "Days":  0,
                                                                                           "Hours":  0,
                                                                                           "Milliseconds":  405,
                                                                                           "Minutes":  0,
                                                                                           "Seconds":  1,
                                                                                           "TotalDays":  1.6264810185185185E-05,
                                                                                           "TotalHours":  0.00039035544444444441,
                                                                                           "TotalMilliseconds":  1405.2796,
                                                                                           "TotalMinutes":  0.023421326666666666,
                                                                                           "TotalSeconds":  1.4052795999999999
                                                                                       },
                                                                          "Timestamp":  {
                                                                                            "value":  "\/Date(1744863103217)\/",
                                                                                            "DisplayHint":  2,
                                                                                            "DateTime":  "17 апреля 2025 г. 7:11:43"
                                                                                        }
                                                                      },
    "check_errors.py-python-check_errors.py-04BAEB7F1938341A2E1F940D0EB1C228BD82886E":  {
                                                                                            "FilesHash":  "04BAEB7F1938341A2E1F940D0EB1C228BD82886E",
                                                                                            "Error":  null,
                                                                                            "Command":  "python check_errors.py",
                                                                                            "Success":  false,
                                                                                            "Output":  "C:\\Program Files\\Python311\\python.exe: can\u0027t open file \u0027D:\\\\dmarket_trading_bot\\\\check_errors.py\u0027: [Errno 2] No such file or directory",
                                                                                            "Name":  "check_errors.py",
                                                                                            "StartTime":  "\/Date(1744863137149)\/",
                                                                                            "ExitCode":  2,
                                                                                            "EndTime":  "\/Date(1744863137193)\/",
                                                                                            "Duration":  {
                                                                                                             "Ticks":  440401,
                                                                                                             "Days":  0,
                                                                                                             "Hours":  0,
                                                                                                             "Milliseconds":  44,
                                                                                                             "Minutes":  0,
                                                                                                             "Seconds":  0,
                                                                                                             "TotalDays":  5.0972337962962962E-07,
                                                                                                             "TotalHours":  1.2233361111111111E-05,
                                                                                                             "TotalMilliseconds":  44.0401,
                                                                                                             "TotalMinutes":  0.00073400166666666672,
                                                                                                             "TotalSeconds":  0.0440401
                                                                                                         },
                                                                                            "Timestamp":  {
                                                                                                              "value":  "\/Date(1744863137193)\/",
                                                                                                              "DisplayHint":  2,
                                                                                                              "DateTime":  "17 апреля 2025 г. 7:12:17"
                                                                                                          }
                                                                                        },
    "pylint-python--m pylint --output-format=text -04BAEB7F1938341A2E1F940D0EB1C228BD82886E":  {
                                                                                                   "FilesHash":  "04BAEB7F1938341A2E1F940D0EB1C228BD82886E",
                                                                                                   "Error":  null,
                                                                                                   "Command":  "python -m pylint --output-format=text ",
                                                                                                   "Success":  false,
                                                                                                   "Output":  [
                                                                                                                  "************* Module D:\\dmarket_trading_bot\\.pylintrc",
                                                                                                                  ".pylintrc:1:0: F0011: error while parsing the configuration: Source contains parsing errors: \u0027D:\\\\dmarket_trading_bot\\\\.pylintrc\u0027",
                                                                                                                  "\t[line 15]: \u0027missing-docstring,\\n\u0027",
                                                                                                                  "\t[line 54]: \u0027numpy,torch,optparse.Values,thread._local,_thread._local\\n\u0027 (config-parse-error)",
                                                                                                                  "No files to lint: exiting."
                                                                                                              ],
                                                                                                   "Name":  "pylint",
                                                                                                   "StartTime":  "\/Date(1744863097656)\/",
                                                                                                   "ExitCode":  32,
                                                                                                   "EndTime":  "\/Date(1744863098015)\/",
                                                                                                   "Duration":  {
                                                                                                                    "Ticks":  3583375,
                                                                                                                    "Days":  0,
                                                                                                                    "Hours":  0,
                                                                                                                    "Milliseconds":  358,
                                                                                                                    "Minutes":  0,
                                                                                                                    "Seconds":  0,
                                                                                                                    "TotalDays":  4.1474247685185184E-06,
                                                                                                                    "TotalHours":  9.9538194444444441E-05,
                                                                                                                    "TotalMilliseconds":  358.33750000000003,
                                                                                                                    "TotalMinutes":  0.0059722916666666665,
                                                                                                                    "TotalSeconds":  0.3583375
                                                                                                                },
                                                                                                   "Timestamp":  {
                                                                                                                     "value":  "\/Date(1744863098016)\/",
                                                                                                                     "DisplayHint":  2,
                                                                                                                     "DateTime":  "17 апреля 2025 г. 7:11:38"
                                                                                                                 }
                                                                                               },
    "check_imports.py-python-check_imports.py-04BAEB7F1938341A2E1F940D0EB1C228BD82886E":  {
                                                                                              "FilesHash":  "04BAEB7F1938341A2E1F940D0EB1C228BD82886E",
                                                                                              "Error":  null,
                                                                                              "Command":  "python check_imports.py",
                                                                                              "Success":  false,
                                                                                              "Output":  "C:\\Program Files\\Python311\\python.exe: can\u0027t open file \u0027D:\\\\dmarket_trading_bot\\\\check_imports.py\u0027: [Errno 2] No such file or directory",
                                                                                              "Name":  "check_imports.py",
                                                                                              "StartTime":  "\/Date(1744863125833)\/",
                                                                                              "ExitCode":  2,
                                                                                              "EndTime":  "\/Date(1744863125879)\/",
                                                                                              "Duration":  {
                                                                                                               "Ticks":  460415,
                                                                                                               "Days":  0,
                                                                                                               "Hours":  0,
                                                                                                               "Milliseconds":  46,
                                                                                                               "Minutes":  0,
                                                                                                               "Seconds":  0,
                                                                                                               "TotalDays":  5.3288773148148146E-07,
                                                                                                               "TotalHours":  1.2789305555555556E-05,
                                                                                                               "TotalMilliseconds":  46.0415,
                                                                                                               "TotalMinutes":  0.00076735833333333337,
                                                                                                               "TotalSeconds":  0.0460415
                                                                                                           },
                                                                                              "Timestamp":  {
                                                                                                                "value":  "\/Date(1744863125879)\/",
                                                                                                                "DisplayHint":  2,
                                                                                                                "DateTime":  "17 апреля 2025 г. 7:12:05"
                                                                                                            }
                                                                                          },
    "pytest-python--m pytest -04BAEB7F1938341A2E1F940D0EB1C228BD82886E":  {
                                                                              "FilesHash":  "04BAEB7F1938341A2E1F940D0EB1C228BD82886E",
                                                                              "Error":  null,
                                                                              "Command":  "python -m pytest ",
                                                                              "Success":  false,
                                                                              "Output":  [
                                                                                             "============================= test session starts =============================",
                                                                                             "platform win32 -- Python 3.11.9, pytest-7.4.3, pluggy-1.5.0",
                                                                                             "rootdir: D:\\dmarket_trading_bot",
                                                                                             "configfile: pyproject.toml",
                                                                                             "testpaths: tests",
                                                                                             "plugins: anyio-4.9.0, asyncio-0.21.1, cov-4.1.0",
                                                                                             "asyncio: mode=Mode.STRICT",
                                                                                             "collected 184 items / 6 errors",
                                                                                             "=================================== ERRORS ====================================",
                                                                                             "_____________________ ERROR collecting tests/test_cli.py ______________________",
                                                                                             "ImportError while importing test module \u0027D:\\dmarket_trading_bot\\tests\\test_cli.py\u0027.",
                                                                                             "Hint: make sure your test modules/packages have valid Python names.",
                                                                                             "Traceback:",
                                                                                             "C:\\Program Files\\Python311\\Lib\\importlib\\__init__.py:126: in import_module",
                                                                                             "    return _bootstrap._gcd_import(name[level:], package, level)",
                                                                                             "tests\\test_cli.py:22: in \u003cmodule\u003e",
                                                                                             "    from src.cli.cli import parse_args, main",
                                                                                             "src\\cli\\cli.py:28: in \u003cmodule\u003e",
                                                                                             "    from src.api.integration import IntegrationManager",
                                                                                             "src\\api\\integration.py:18: in \u003cmodule\u003e",
                                                                                             "    from src.db.db_funcs import (",
                                                                                             "src\\db\\db_funcs.py:15: in \u003cmodule\u003e",
                                                                                             "    from sqlalchemy import create_engine, Column, Integer, String, Float, DateTime, Boolean, ForeignKey",
                                                                                             "E   ModuleNotFoundError: No module named \u0027sqlalchemy\u0027",
                                                                                             "_________________ ERROR collecting tests/test_integration.py __________________",
                                                                                             "ImportError while importing test module \u0027D:\\dmarket_trading_bot\\tests\\test_integration.py\u0027.",
                                                                                             "Hint: make sure your test modules/packages have valid Python names.",
                                                                                             "Traceback:",
                                                                                             "C:\\Program Files\\Python311\\Lib\\importlib\\__init__.py:126: in import_module",
                                                                                             "    return _bootstrap._gcd_import(name[level:], package, level)",
                                                                                             "tests\\test_integration.py:23: in \u003cmodule\u003e",
                                                                                             "    from src.api.dmarket_api import DMarketAPI",
                                                                                             "E   ModuleNotFoundError: No module named \u0027src.api.dmarket_api\u0027",
                                                                                             "____________ ERROR collecting tests/test_marketplace_integrator.py ____________",
                                                                                             "ImportError while importing test module \u0027D:\\dmarket_trading_bot\\tests\\test_marketplace_integrator.py\u0027.",
                                                                                             "Hint: make sure your test modules/packages have valid Python names.",
                                                                                             "Traceback:",
                                                                                             "C:\\Program Files\\Python311\\Lib\\importlib\\__init__.py:126: in import_module",
                                                                                             "    return _bootstrap._gcd_import(name[level:], package, level)",
                                                                                             "tests\\test_marketplace_integrator.py:21: in \u003cmodule\u003e",
                                                                                             "    from utils.marketplace_integrator import MarketplaceIntegrator",
                                                                                             "utils\\marketplace_integrator.py:17: in \u003cmodule\u003e",
                                                                                             "    from utils.marketplace_api import (",
                                                                                             "utils\\marketplace_api.py:19: in \u003cmodule\u003e",
                                                                                             "    import pyotp",
                                                                                             "E   ModuleNotFoundError: No module named \u0027pyotp\u0027",
                                                                                             "___________________ ERROR collecting tests/cli/test_cli.py ____________________",
                                                                                             "dmarket_bot_env\\Lib\\site-packages\\_pytest\\runner.py:341: in from_call",
                                                                                             "    result: Optional[TResult] = func()",
                                                                                             "dmarket_bot_env\\Lib\\site-packages\\_pytest\\runner.py:372: in \u003clambda\u003e",
                                                                                             "    call = CallInfo.from_call(lambda: list(collector.collect()), \"collect\")",
                                                                                             "dmarket_bot_env\\Lib\\site-packages\\_pytest\\python.py:531: in collect",
                                                                                             "    self._inject_setup_module_fixture()",
                                                                                             "dmarket_bot_env\\Lib\\site-packages\\_pytest\\python.py:545: in _inject_setup_module_fixture",
                                                                                             "    self.obj, (\"setUpModule\", \"setup_module\")",
                                                                                             "dmarket_bot_env\\Lib\\site-packages\\_pytest\\python.py:310: in obj",
                                                                                             "    self._obj = obj = self._getobj()",
                                                                                             "dmarket_bot_env\\Lib\\site-packages\\_pytest\\python.py:528: in _getobj",
                                                                                             "    return self._importtestmodule()",
                                                                                             "dmarket_bot_env\\Lib\\site-packages\\_pytest\\python.py:617: in _importtestmodule",
                                                                                             "    mod = import_path(self.path, mode=importmode, root=self.config.rootpath)",
                                                                                             "dmarket_bot_env\\Lib\\site-packages\\_pytest\\pathlib.py:567: in import_path",
                                                                                             "    importlib.import_module(module_name)",
                                                                                             "C:\\Program Files\\Python311\\Lib\\importlib\\__init__.py:126: in import_module",
                                                                                             "    return _bootstrap._gcd_import(name[level:], package, level)",
                                                                                             "\u003cfrozen importlib._bootstrap\u003e:1204: in _gcd_import",
                                                                                             "    ???",
                                                                                             "\u003cfrozen importlib._bootstrap\u003e:1176: in _find_and_load",
                                                                                             "    ???",
                                                                                             "\u003cfrozen importlib._bootstrap\u003e:1147: in _find_and_load_unlocked",
                                                                                             "    ???",
                                                                                             "\u003cfrozen importlib._bootstrap\u003e:690: in _load_unlocked",
                                                                                             "    ???",
                                                                                             "dmarket_bot_env\\Lib\\site-packages\\_pytest\\assertion\\rewrite.py:186: in exec_module",
                                                                                             "    exec(co, module.__dict__)",
                                                                                             "tests\\cli\\test_cli.py:33: in \u003cmodule\u003e",
                                                                                             "    class TestCLI(unittest.TestCase):",
                                                                                             "tests\\cli\\test_cli.py:204: in TestCLI",
                                                                                             "    @patch(\u0027sys.argv\u0027, [\u0027cli.py\u0027, \u0027run\u0027, \u0027--api-keys\u0027, self.api_keys_file, \u0027--timeout\u0027, \u002710\u0027])",
                                                                                             "E   NameError: name \u0027self\u0027 is not defined",
                                                                                             "_____________ ERROR collecting tests/utils/test_error_handling.py _____________",
                                                                                             "ImportError while importing test module \u0027D:\\dmarket_trading_bot\\tests\\utils\\test_error_handling.py\u0027.",
                                                                                             "Hint: make sure your test modules/packages have valid Python names.",
                                                                                             "Traceback:",
                                                                                             "C:\\Program Files\\Python311\\Lib\\importlib\\__init__.py:126: in import_module",
                                                                                             "    return _bootstrap._gcd_import(name[level:], package, level)",
                                                                                             "tests\\utils\\test_error_handling.py:16: in \u003cmodule\u003e",
                                                                                             "    from src.utils.error_handling import (",
                                                                                             "E   ImportError: cannot import name \u0027log_execution_time\u0027 from \u0027src.utils.error_handling\u0027 (D:\\dmarket_trading_bot\\src\\utils\\error_handling.py)",
                                                                                             "_____________ ERROR collecting tests/utils/test_secure_config.py ______________",
                                                                                             "ImportError while importing test module \u0027D:\\dmarket_trading_bot\\tests\\utils\\test_secure_config.py\u0027.",
                                                                                             "Hint: make sure your test modules/packages have valid Python names.",
                                                                                             "Traceback:",
                                                                                             "C:\\Program Files\\Python311\\Lib\\importlib\\__init__.py:126: in import_module",
                                                                                             "    return _bootstrap._gcd_import(name[level:], package, level)",
                                                                                             "tests\\utils\\test_secure_config.py:20: in \u003cmodule\u003e",
                                                                                             "    from src.utils.secure_config import (",
                                                                                             "src\\utils\\secure_config.py:35: in \u003cmodule\u003e",
                                                                                             "    from src.utils.error_handling import (",
                                                                                             "E   ImportError: cannot import name \u0027BotError\u0027 from \u0027src.utils.error_handling\u0027 (D:\\dmarket_trading_bot\\src\\utils\\error_handling.py)",
                                                                                             "============================== warnings summary ===============================",
                                                                                             "tests\\test_api.py:9",
                                                                                             "  d:\\dmarket_trading_bot\\tests\\test_api.py:9: DeprecationWarning: Importing from api_wrapper.py at project root is deprecated. Use \u0027from src.api import api_wrapper\u0027 instead.",
                                                                                             "    from api_wrapper import DMarketAPI, APIError, AuthenticationError, RateLimitError, NetworkError",
                                                                                             "dmarket_bot_env\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py:293",
                                                                                             "dmarket_bot_env\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py:293",
                                                                                             "  D:\\dmarket_trading_bot\\dmarket_bot_env\\Lib\\site-packages\\pydantic\\_internal\\_generate_schema.py:293: PydanticDeprecatedSince20: `json_encoders` is deprecated. See https://docs.pydantic.dev/2.11/concepts/serialization/#custom-serializers for alternatives. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/",
                                                                                             "    warnings.warn(",
                                                                                             "-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html",
                                                                                             "=========================== short test summary info ===========================",
                                                                                             "ERROR tests/test_cli.py",
                                                                                             "ERROR tests/test_integration.py",
                                                                                             "ERROR tests/test_marketplace_integrator.py",
                                                                                             "ERROR tests/cli/test_cli.py - NameError: name \u0027self\u0027 is not defined",
                                                                                             "ERROR tests/utils/test_error_handling.py",
                                                                                             "ERROR tests/utils/test_secure_config.py",
                                                                                             "!!!!!!!!!!!!!!!!!!! Interrupted: 6 errors during collection !!!!!!!!!!!!!!!!!!!",
                                                                                             "======================= 3 warnings, 6 errors in 10.01s ========================"
                                                                                         ],
                                                                              "Name":  "pytest",
                                                                              "StartTime":  "\/Date(1744863111301)\/",
                                                                              "ExitCode":  2,
                                                                              "EndTime":  "\/Date(1744863122085)\/",
                                                                              "Duration":  {
                                                                                               "Ticks":  107838095,
                                                                                               "Days":  0,
                                                                                               "Hours":  0,
                                                                                               "Milliseconds":  783,
                                                                                               "Minutes":  0,
                                                                                               "Seconds":  10,
                                                                                               "TotalDays":  0.0001248126099537037,
                                                                                               "TotalHours":  0.0029955026388888886,
                                                                                               "TotalMilliseconds":  10783.809500000001,
                                                                                               "TotalMinutes":  0.17973015833333333,
                                                                                               "TotalSeconds":  10.7838095
                                                                                           },
                                                                              "Timestamp":  {
                                                                                                "value":  "\/Date(1744863122086)\/",
                                                                                                "DisplayHint":  2,
                                                                                                "DateTime":  "17 апреля 2025 г. 7:12:02"
                                                                                            }
                                                                          }
}